/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.nateweisz.app;

import me.nateweisz.list.LinkedList;

import static me.nateweisz.utilities.StringUtils.join;
import static me.nateweisz.utilities.StringUtils.split;
import static me.nateweisz.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
