[package]
name = "minion"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = ["full"] }
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"] }
